<a href="https://colab.research.google.com/github/Roshan-234/ML-Projects/blob/main/Todays_price_Prediction_NEPSE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Step 1: Data Preprocessing
# Read the dataset from a CSV file or any other data source
df = pd.read_excel("Today's Price _2023-07-16.xlsx")

In [3]:
df.head()

,S.N,BUSINESS_DATE,SECURITY_ID,SYMBOL,SECURITY_NAME,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,TOTAL_TRADED_QUANTITY,TOTAL_TRADED_VALUE,PREVIOUS_DAY_CLOSE_PRICE,FIFTY_TWO_WEEKS_HIGH,FIFTY_TWO_WEEKS_LOW,LAST_UPDATED_PRICE,TOTAL_TRADES,AVERAGE_TRADED_PRICE,MARKET_CAPITALIZATION
0,281,2023-07-16,9179,MEL,Modi Energy Limited,212.0,212.7,205.0,207.5,44573,9268540.5,208.6,275.4,197.9,207.5,2475,207.94,6017.50
1,153,2023-07-16,2809,SHIVM,SHIVAM CEMENTS LTD,655.0,668.0,647.1,651.5,292584,191311372.9,652.2,864.0,389.8,651.5,1525,653.86,28666.00
2,53,2023-07-16,393,HLI,Himalayan Life Insurance Limited,507.0,514.9,504.0,507.0,308820,156945064.5,507.0,574.0,340.0,507.0,1500,508.20,40663.34
3,251,2023-07-16,9173,CITY,City Hotel Limited,695.0,710.0,680.0,680.1,35142,24243439.8,696.1,744.0,111.1,680.1,936,689.87,11384.87
4,184,2023-07-16,2919,NIFRA,Nepal Infrastructure Bank Limited,218.0,228.0,215.9,224.0,173923,38640019.8,217.0,269.2,176.9,224.0,833,222.16,48384.00

In [4]:
drop_column_list = ['BUSINESS_DATE', 'SECURITY_ID']
df.drop(drop_column_list, axis=1, inplace=True)

In [5]:
df.rename(columns={'CLOSE_PRICE': 'SHARE_PRICE'},inplace=True)
parameters = ['OPEN_PRICE', 'HIGH_PRICE', 'LOW_PRICE', 'TOTAL_TRADED_QUANTITY', 'TOTAL_TRADED_VALUE',
              'PREVIOUS_DAY_CLOSE_PRICE', 'FIFTY_TWO_WEEKS_HIGH', 'FIFTY_TWO_WEEKS_LOW', 'LAST_UPDATED_PRICE',
              'TOTAL_TRADES', 'AVERAGE_TRADED_PRICE', 'MARKET_CAPITALIZATION']
df[parameters] = df[parameters].astype(float)

In [6]:
df[parameters].isnull()

,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,TOTAL_TRADED_QUANTITY,TOTAL_TRADED_VALUE,PREVIOUS_DAY_CLOSE_PRICE,FIFTY_TWO_WEEKS_HIGH,FIFTY_TWO_WEEKS_LOW,LAST_UPDATED_PRICE,TOTAL_TRADES,AVERAGE_TRADED_PRICE,MARKET_CAPITALIZATION
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
253,False,False,False,False,False,False,False,False,False,False,False,False
254,False,False,False,False,False,False,False,False,False,False,False,False
255,False,False,False,False,False,False,False,False,False,False,False,False
256,False,False,False,False,False,False,False,False,False,False,False,False
257,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
# Separate the input features (X) and target variable (y)
X = df[['OPEN_PRICE', 'HIGH_PRICE', 'LOW_PRICE', 'TOTAL_TRADED_QUANTITY', 'TOTAL_TRADED_VALUE',
             'PREVIOUS_DAY_CLOSE_PRICE', 'FIFTY_TWO_WEEKS_HIGH', 'FIFTY_TWO_WEEKS_LOW', 'LAST_UPDATED_PRICE',
             'TOTAL_TRADES', 'AVERAGE_TRADED_PRICE', 'MARKET_CAPITALIZATION']]
y = df['SHARE_PRICE']  # Replace "SHARE_PRICE" with the actual column name for the target variable

# Step 3: Train-Test Split
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Model Training
# Create a Random Forest regressor and train it on the training data
regressor = RandomForestRegressor(n_estimators=100, random_state=42)  # Adjust parameters as needed
regressor.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [8]:
# Step 5: Model Evaluation
# Evaluate the model on the testing set
predictions = regressor.predict(X_test)
mse = mean_squared_error(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)

print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)

Mean Squared Error (MSE): 997.8192305528814
Mean Absolute Error (MAE): 12.347594230769166

In [11]:
# Step 6: Prediction
# Use the trained model to make predictions on new, unseen data
new_data = pd.DataFrame([[475, 499, 475, 364928, 179294561.9, 480.1, 536, 191.8, 486, 767, 491.31, 42997.15]],
                        columns=X.columns)



new_prediction = regressor.predict(new_data)

print("Predicted Share Market Price:", new_prediction)

Predicted Share Market Price: [488.165]