<a href="https://colab.research.google.com/github/Roshan-234/ML-Projects/blob/main/Todays_price_Prediction_NEPSE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Step 1: Data Preprocessing
# Read the dataset from a CSV file or any other data source
df = pd.read_excel("Today's Price _2023-07-16.xlsx")

In [77]:
df.head()

,BUSINESS_DATE,SECURITY_ID,SYMBOL,SECURITY_NAME,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,TOTAL_TRADED_QUANTITY,TOTAL_TRADED_VALUE,PREVIOUS_DAY_CLOSE_PRICE,FIFTY_TWO_WEEKS_HIGH,FIFTY_TWO_WEEKS_LOW,LAST_UPDATED_PRICE,TOTAL_TRADES,AVERAGE_TRADED_PRICE,MARKET_CAPITALIZATION
0,2023-07-16,9179,MEL,Modi Energy Limited,212.0,212.7,205.0,207.5,44573,9268540.5,208.6,275.4,197.9,207.5,2475,207.94,6017.50
1,2023-07-16,2809,SHIVM,SHIVAM CEMENTS LTD,655.0,668.0,647.1,651.5,292584,191311372.9,652.2,864.0,389.8,651.5,1525,653.86,28666.00
2,2023-07-16,393,HLI,Himalayan Life Insurance Limited,507.0,514.9,504.0,507.0,308820,156945064.5,507.0,574.0,340.0,507.0,1500,508.20,40663.34
3,2023-07-16,9173,CITY,City Hotel Limited,695.0,710.0,680.0,680.1,35142,24243439.8,696.1,744.0,111.1,680.1,936,689.87,11384.87
4,2023-07-16,2919,NIFRA,Nepal Infrastructure Bank Limited,218.0,228.0,215.9,224.0,173923,38640019.8,217.0,269.2,176.9,224.0,833,222.16,48384.00

In [78]:
# drop_column_list = ['BUSINESS_DATE', 'SECURITY_ID']
# df.drop(drop_column_list, axis=1, inplace=True)

In [79]:
df.rename(columns={'CLOSE_PRICE': 'SHARE_PRICE'},inplace=True)
parameters = ['OPEN_PRICE', 'HIGH_PRICE', 'LOW_PRICE', 'TOTAL_TRADED_QUANTITY', 'TOTAL_TRADED_VALUE',
              'PREVIOUS_DAY_CLOSE_PRICE', 'FIFTY_TWO_WEEKS_HIGH', 'FIFTY_TWO_WEEKS_LOW', 'LAST_UPDATED_PRICE',
              'TOTAL_TRADES', 'AVERAGE_TRADED_PRICE']
df[parameters] = df[parameters].astype(float)

In [80]:
df[parameters].isnull()

,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,TOTAL_TRADED_QUANTITY,TOTAL_TRADED_VALUE,PREVIOUS_DAY_CLOSE_PRICE,FIFTY_TWO_WEEKS_HIGH,FIFTY_TWO_WEEKS_LOW,LAST_UPDATED_PRICE,TOTAL_TRADES,AVERAGE_TRADED_PRICE
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1056,False,False,False,False,False,False,False,False,False,False,False
1057,False,False,False,False,False,False,False,False,False,False,False
1058,False,False,False,False,False,False,False,False,False,False,False
1059,False,False,False,False,False,False,False,False,False,False,False
1060,False,False,False,False,False,False,False,False,False,False,False

In [81]:
# Separate the input features (X) and target variable (y)
X = df[['OPEN_PRICE', 'HIGH_PRICE', 'LOW_PRICE', 'TOTAL_TRADED_QUANTITY', 'TOTAL_TRADED_VALUE',
             'PREVIOUS_DAY_CLOSE_PRICE', 'FIFTY_TWO_WEEKS_HIGH', 'FIFTY_TWO_WEEKS_LOW', 'LAST_UPDATED_PRICE',
             'TOTAL_TRADES', 'AVERAGE_TRADED_PRICE']]
y = df['SHARE_PRICE']  # Replace "SHARE_PRICE" with the actual column name for the target variable

# Step 3: Train-Test Split
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Model Training
# Create a Random Forest regressor and train it on the training data
regressor = RandomForestRegressor(n_estimators=100, random_state=42)
regressor.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [82]:
# Step 5: Model Evaluation
# Evaluate the model on the testing set
predictions = regressor.predict(X_test)
mse = mean_squared_error(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)

print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)

Mean Squared Error (MSE): 5874.274039901695
Mean Absolute Error (MAE): 11.410684507042228

In [83]:
# Step 6: Prediction
# Use the trained model to make predictions on new, unseen data
# 'OPEN_PRICE', 'HIGH_PRICE', 'LOW_PRICE', 'TOTAL_TRADED_QUANTITY', 'TOTAL_TRADED_VALUE',
#              'PREVIOUS_DAY_CLOSE_PRICE', 'FIFTY_TWO_WEEKS_HIGH', 'FIFTY_TWO_WEEKS_LOW', 'LAST_UPDATED_PRICE',
#              'TOTAL_TRADES', 'AVERAGE_TRADED_PRICE'
new_data = pd.DataFrame([[798, 807.00, 789, 55849, 44687582.3, 793.8, 861.90, 600.30, 803.0, 423, 800.15]],
                        columns=X.columns)
new_prediction = regressor.predict(new_data)


print("Predicted Share Market Price:", new_prediction)

Predicted Share Market Price: [802.45]

In [84]:
new_data = pd.DataFrame([[518.90, 538.40, 499.20, 2214, 1180437.4, 489.49, 518.90, 326.00, 538.40, 37, 533.17]],
                        columns=X.columns)
new_prediction = regressor.predict(new_data)
print("Predicted Share Market Price:", new_prediction)

Predicted Share Market Price: [536.683]

In [85]:
new_data = pd.DataFrame([[185.50, 192.00, 184.50, 94010, 17766969.3, 186.00, 251.40, 176.00, 188.00, 507, 188.99]],
                        columns=X.columns)
new_prediction = regressor.predict(new_data)
print("Predicted Share Market Price:", new_prediction)

Predicted Share Market Price: [187.617]

In [86]:
new_data = pd.DataFrame([[744.00, 749, 732, 14208, 10538678, 736.30, 781.00, 497.20, 744.00, 97, 741.74]],
                        columns=X.columns)
new_prediction = regressor.predict(new_data)
print("Predicted Share Market Price:", new_prediction)

Predicted Share Market Price: [743.353]

In [87]:
new_data = pd.DataFrame([[647.00, 676.00, 647.00, 2473, 1642561.9, 647.00, 977.10, 530.00, 673.90, 66, 664.20]],
                        columns=X.columns)
new_prediction = regressor.predict(new_data)
print("Predicted Share Market Price:", new_prediction)

Predicted Share Market Price: [671.893]

In [88]:
import joblib
joblib.dump(regressor, 'trained_model.pkl')

['trained_model.pkl']